name: Python Script Execution

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Increase overall job timeout
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl

    - name: Configure pip
      run: |
        python -m pip config set global.disable-pip-version-check true
        python -m pip config set global.no-cache-dir true
    
    - name: Install Dependencies
      env:
        PIP_DISABLE_PIP_VERSION_CHECK: 1
        PIP_NO_CACHE_DIR: 1
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
        python -m pip install --timeout 300 -r requirements.txt
    
    - name: Troubleshoot Dependencies
      if: failure()
      run: |
        pip install -v -r requirements.txt --no-cache-dir
        pip list
        python -c "import sys; print(sys.version)"
    
    - name: Run Script
      run: |
        python feature_pipeline.py
      continue-on-error: true  # Prevents workflow from failing completely