name: Python Dependency Installation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-script:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.9', '3.10']
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install System Dependencies
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          sudo apt-get update
          sudo apt-get install -y build-essential
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          brew install gcc
        fi
    
    - name: Upgrade pip and setuptools
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
    
    - name: Install Dependencies with Retry
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: |
          pip install -r requirements.txt --no-cache-dir
    
    - name: Verify Installation
      run: |
        pip list
        python -c "import numpy; import pandas; print('Dependencies successfully imported!')"