
name: Run Script Every 3 Days

on:
 push

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.0

    - name: Install Dependencies
      env:
        API_KEY: ${{ secrets.API_KEY }}
        BASE_URL: ${{ secrets.BASE_URL }}
      run: |
        pip install -r requirements.txt  # If your script has dependencies

    - name: Run the Script
      run: |
        python feature_pipeline.py  # Replace with the name of your script

        - name: Set up Git configuration
        run: |
          git config --global user.name "Parviz822"
          git config --global user.email "perviz822@gmail.com"
  
    - name: Commit and Push Changes
      run: |

          git add baku_air_quality_data.csv  # The path to your CSV file
          git diff --cached --quiet || git commit -m "Update air quality data CSV"
          git push origin HEAD:main  # Replace 'main' with your branch name if needed
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
