name: Python Dependency Installation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install System Dependencies
        run: |
          brew update
          brew install openssl
          brew install libffi
      
      - name: Prepare Dependency Installation
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install pip-tools
      
      - name: Generate Locked Requirements
        run: |
          pip-compile requirements.txt -o requirements.lock
      
      - name: Install Dependencies with Advanced Options
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1
          PIP_NO_CACHE_DIR: 1
        run: |
          pip install \
            --no-cache-dir \
            --no-deps \
            --ignore-installed \
            --upgrade \
            -r requirements.lock
      
      - name: Verify Dependencies
        run: |
          pip list
          python -c "import requests; import dotenv; print('Dependencies successfully imported!')"
      
      - name: Run Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          python feature_pipeline.py
        
      - name: Troubleshoot if Failure
        if: failure()
        run: |
          pip install -v -r requirements.lock
          python -m pip debug
          python -c "import sys; print(sys.version)"