
name: Run Script Every 3 Days

on:
 push

env:
  API_KEY: ${{ secrets.API_KEY }}
  BASE_URL: ${{ secrets.BASE_URL }}
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.0

    - name: Install Dependencies
     
      run: |
        pip install -r requirements.txt  # If your script has dependencies

    - name: Run the Script
      run: |
        python feature_pipeline.py  # Replace with the name of your script
  
    - name: Commit and Push Changes
      run: |
          git config --local user.email "perviz822@gmail.com"
          git config --local user.name "Parviz"
          git add baku_aqi.csv
          git commit -m "AQI data was updated"
          git push
      
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
