name: Run Script Every 3 Days

on:
  push

jobs:
  run-script:
    runs-on: macos-latest 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          pip install --upgrade pip  # Upgrade pip to the latest version
        

      - name: Run the Script
        run: |
          python feature_pipeline.py  # Replace with the name of your script